name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    deploy:
        name: Deploy to Heroku
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
          id: heroku
          uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
          with:
            email: peter.chau.esq@gmail.com
            api_key: e2a19921-3878-477f-bb83-27662dc28b5c
            app_name: hanashi-san
            dockerfile_path: 'dockerfile'
#            options: '' # Docker Build Options
